/* config.h.  Generated by configure.  */
/* package */
#define PACKAGE "mbuffer"

/* version of mbuffer */
#define VERSION "20060217"

/* Define if you want support for debugging messages. */
#define DEBUG 1

/* Undefine if you want asserts enabled. */
/* #undef NDEBUG */

/* md5hashing is enabled by default,
   default is libmhash fallback is libmd5 */
/* #undef HAVE_LIBMHASH */
#define HAVE_LIBMD5 1
/* #undef HAVE_LIBSSL */

/* Define if you have a working `mmap' system call.  */
#define HAVE_MMAP 1

/* Define as the return type of signal handlers (int or void).  */
#define RETSIGTYPE void

/* Needed for thread safe compilation */
#define _REENTRANT 1

/* Define if you have the strerror function.  */
#define HAVE_STRERROR 1

/* Define to 1 if your `struct stat' has `st_blksize'. Deprecated, use
   `HAVE_STRUCT_STAT_ST_BLKSIZE' instead. */
#define HAVE_ST_BLKSIZE 1

/* Define if `st_blksize' is member of `struct stat'. */
#define HAVE_STRUCT_STAT_ST_BLKSIZE 1

/* Define if you have libsendfile. */
#define HAVE_SENDFILE 1
