/* config.h.  Generated by configure.  */
/* package */
#define PACKAGE "mbuffer"

/* version of mbuffer */
#define VERSION "20060704"

/* Define if you want support for debugging messages. */
#define DEBUG 1

/* Undefine if you want asserts enabled. */
/* #undef NDEBUG */

/* md5hashing is enabled by default,
   default is libmhash fallback is libmd5 */
/* #undef HAVE_LIBMHASH */
/* #undef HAVE_LIBMD5 */
#define HAVE_LIBSSL 1

/* Define if you have a working `mmap' system call.  */
/* #undef HAVE_MMAP */

/* Define as the return type of signal handlers (int or void).  */
#define RETSIGTYPE void

/* Needed for thread safe compilation */
#define _REENTRANT 1

/* Define if you have the strerror function.  */
/* #undef HAVE_STRERROR */

/* Define to 1 if your `struct stat' has `st_blksize'. Deprecated, use
   `HAVE_STRUCT_STAT_ST_BLKSIZE' instead. */
/* #undef HAVE_ST_BLKSIZE */

/* Define if `st_blksize' is member of `struct stat'. */
/* #undef HAVE_STRUCT_STAT_ST_BLKSIZE */

/* Define if you have libsendfile. */
#define HAVE_SENDFILE 1

/* largefile support */
/* #undef _LARGE_FILE */
/* #undef _LARGEFILE_SOURCE */
/* #undef _LARGEFILE64_SOURCE */
#define _FILE_OFFSET_BITS 64
